[workspace]
resolver = "2"
members = ["crates/rpc", "crates/rupd", "crates/rup"]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.0.0"

[workspace.dependencies]
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros"] }

[workspace.lints.rust]
unsafe_code = "forbid"
unused = { level = "deny", priority = -1 }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
