[package]
name = "messages"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
contracts = { path = "../contracts" }
rpc = { path = "../rpc" }
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true

[dev-dependencies]
provenance = { path = "../provenance" }
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
