[package]
name = "agents"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
contracts = { path = "../contracts" }
rpc = { path = "../rpc" }
rusqlite.workspace = true
serde_json.workspace = true
terminal = { path = "../terminal" }
tempfile.workspace = true
tokio.workspace = true

[dev-dependencies]
provenance = { path = "../provenance" }

[lints]
workspace = true
