[package]
name = "agents"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
contracts = { path = "../contracts" }
rpc = { path = "../rpc" }
rusqlite.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
terminal = { path = "../terminal" }

tokio.workspace = true

[dev-dependencies]
provenance = { path = "../provenance" }
tempfile.workspace = true

[lints]
workspace = true
